#!/usr/bin/env node
/* eslint-disable */
import yargs from "yargs";
import Logger from "../services/LoggerService";

yargs
  .command({
    command: "build-workbench",
    aliases: ["build"],
    desc: "Build a workbench in WinUAE based on the provided duckbench file",
    builder: (yargs) => {
      yargs
        .option("duckbench-file", {
          alias: "db",
          description: 'The ".db" file describing the Workbench install.',
          type: "string",
        })
        .option("logLevel", {
          alias: "l",
          description: "Log level for the execution",
          choices: [
            "all",
            "trace",
            "debug",
            "info",
            "warn",
            "error",
            "fatal",
            "none",
          ],
          default: "info",
        })
        .demandOption("duckbench-file");
    },
    handler: async (args) => {
      await import("../services/LoggerService");
      Logger.level = args.logLevel;
      await import("../services/BaseDirService");
      import Communicator from "../builder/Communicator.ts";
      import DuckbenchBuilder from "../builder/DuckbenchBuilder.ts";
      import WinUAEEnvironment from "../builder/WinUAEEnvironment.ts";

      const duckbenchBuilder = new DuckbenchBuilder();
      await duckbenchBuilder.build(
        JSON.parse(readFileSync(args.db)),
        WinUAEEnvironment,
        Communicator,
      );
    },
  })
  .command({
    command: "*",
    desc: "Start up the duckbench configurator",
    builder: (yargs) => {
      yargs.option("logLevel", {
        alias: "l",
        description: "Log level for the execution",
        choices: [
          "all",
          "trace",
          "debug",
          "info",
          "warn",
          "error",
          "fatal",
          "none",
        ],
        default: "info",
      });
    },
    handler: async (args) => {
      await import("../services/LoggerService");
      Logger.level = args.logLevel;
      await import("../services/BaseDirService");
      import Configurator from "../configurator/Configurator";

      const configurator = new Configurator();
      configurator.start();
    },
  })
  .help()
  .alias("help", "h")
  .strict().argv;
